coupon:
  notification:
    expiry:
      cron: 0 0 9 ? * *
      days:
        before: 3
      message-template: "쿠폰이 %d일 후 만료됩니다."


spring.profiles.active: default
spring.jackson.date-format: yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone: Asia/Seoul


spring.datasource:
  platform: h2
  url: jdbc:h2:mem:coupondb
  username: sa
  password:
  driverClassName: org.h2.Driver
  ## Pool Info ##
  tomcat:
    maxActive: 10
    initialSize: 10
    minIdle: 10
    testOnBorrow: true
    validationQuery: select 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 600000 #10 min
    minEvictableIdleTimeMillis: 600000  #10 min
    validationQueryTimeout: 5
    continue-on-error: true

# JPA Hibernate
spring.jpa:
  hibernate.ddl-auto: create
  database: H2
  properties.hibernate.format_sql: true
  properties.hibernate.use_sql_comments: true
  show-sql: false

spring:
  jpa:
    properties:
      hibernate.enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: true
      path: /h2
